import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import type { Metadata } from 'next';
import NotificationProvider from '@/components/providers/NotificationProvider';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const satoshiVariable = localFont({
    src: '../../public/assets/font/Satoshi-Variable.ttf',
    variable: '--font-satoshi-variable',
});

const clashGroteskVariable = localFont({
    src: '../../public/assets/font/ClashGrotesk-Variable.ttf',
    variable: '--font-clash-grotesk-variable',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${satoshiVariable.variable} ${clashGroteskVariable.variable} antialiased`}>
                <NotificationProvider>{children}</NotificationProvider>
                <Toaster />
            </body>
        </html>
    );
}
